### ISSUE TITLE
getLocalTime fails to return true

### ISSUE THREAD

**Issue by usaotearoa** [RalphBacon/254-ESP32-Pond-Controller#1]
Hi Ralph,
I have an issue with parts of the libraries in your project and was hoping you can help me get to the bottom of it.

Hardware used:
Espressif ESP32 Devkit-4
CPU frequency reported as 240MHz by 
```
uint32_t f = getCpuFrequencyMhz();
Serial.printf("CPU Frequency = %d MHz", f);
```
What appears to happen is, that the function `bool getLocalTime(struct tm * info, uint32_t ms)` in the `esp32-hal-time.c ` gets hung up in the `while((millis()-start) <= ms)` loop. 

To troubleshoot this problem I have modified the getLocalTime function and added some debug logger entries, as so:
```
bool getLocalTime(struct tm * info, uint32_t ms)
{
    uint32_t start = millis();
    time_t now;
    log_e("Debug0: getLocalTime - now %d", now);
    log_e("Debug1: getLocalTime - start %d", start);
    log_e("Debug2: getLocalTime - ms %d", ms);
    log_e("Debug3: getLocalTime - (millis()-start) %d", (millis()-start));
    log_e("Debug4: getLocalTime - tm_year %d", info->tm_year);
    log_e("Debug5: getLocalTime - tm_hour %d", info->tm_hour);
    log_e("Debug6: getLocalTime - tm_min %d", info->tm_min);
    log_e("Debug7: getLocalTime - tm_sec %d", info->tm_sec);

    while((millis()-start) <= ms) {
        time(&now);
        localtime_r(&now, info);
        if(info->tm_year > (2016 - 1900)){
            return true;
        }
        delay(10);
    }
    return false;
}
```

This gives me the following console output, but I'm not sure what to make of it :-/
```
[E][esp32-hal-time.c:84] getLocalTime(): Debug0: getLocalTime - now 1061168511
[E][esp32-hal-time.c:85] getLocalTime(): Debug1: getLocalTime - start 1388840
[E][esp32-hal-time.c:86] getLocalTime(): Debug2: getLocalTime - ms 5000
[E][esp32-hal-time.c:87] getLocalTime(): Debug3: getLocalTime - (millis()-start) 20
[E][esp32-hal-time.c:88] getLocalTime(): Debug4: getLocalTime - tm_year 70
[E][esp32-hal-time.c:89] getLocalTime(): Debug5: getLocalTime - tm_hour 0
[E][esp32-hal-time.c:90] getLocalTime(): Debug6: getLocalTime - tm_min 23
[E][esp32-hal-time.c:91] getLocalTime(): Debug7: getLocalTime - tm_sec 7
```

and again a little later
```
[V][ntpHelper.h:92] getCurrentTime(): Re-trying to get local time, attempt: 3
[E][esp32-hal-time.c:84] getLocalTime(): Debug0: getLocalTime - now 1061168549
[E][esp32-hal-time.c:85] getLocalTime(): Debug1: getLocalTime - start 1406918
[E][esp32-hal-time.c:86] getLocalTime(): Debug2: getLocalTime - ms 5000
[E][esp32-hal-time.c:87] getLocalTime(): Debug3: getLocalTime - (millis()-start) 9
[E][esp32-hal-time.c:88] getLocalTime(): Debug4: getLocalTime - tm_year 70
[E][esp32-hal-time.c:89] getLocalTime(): Debug5: getLocalTime - tm_hour 0
[E][esp32-hal-time.c:90] getLocalTime(): Debug6: getLocalTime - tm_min 23
[E][esp32-hal-time.c:91] getLocalTime(): Debug7: getLocalTime - tm_sec 25
[E][ntpHelper.h:69] getTime(): Failed to obtain local time
```

I have also added some more debug logic to get the "actual time" printed:

```
[E][ntpHelper.h:70] getTime(): ------------------------------------------------------
[E][ntpHelper.h:72] getTime(): Current date/time is 01/01/1970 at 00:00:45
[E][ntpHelper.h:73] getTime(): ------------------------------------------------------
```

There seem to be various loops at play all with their own delays. For example getCurrentTime has a delay of 1000 and calls getTime() five times. Then from getTime() it calls getLocalTime, where it gets hung up in the while. I think that's how it adds up to 30s before actually incrementing a single second. See below.

Further I have added a simple debug output to where the seconds are incremented, to see how long it takes before the seconds count up. It actually seems to be pretty close to 30s before 
```
// Increment seconds counter
secsTime++;
log_e("Incremented secsTime to %d", secsTime);
```
This might be related, but could also be somewhat tied to wrong clock frequencies and therefore the pre-scaler for some timers being off?
It's been a long time (long before Arduino) when I messed with uC's. Just trying to get back into this.

Any chance you can help me get to the bottom of this?

Thanks

**Comment by RalphBacon** [comment]
### Hi usaotearoa

The way the ESP32 gets the time is for it to connect to a valid NTP (Network Time Protocol) server on an infrequent basis. The prerequisite for this to work is that the ESP32 is already connected to your Wi-Fi network. 

Actually, I have my doubts about whether it actually needs to be _logged in_ to your Wi-Fi or just have a _connection_ available. For the purposes of debugging this, ensure your ESP32 is _logged in_ to your Wi-Fi.

You then need to tell it which "pool" of time servers you want to access. Because I live in the UK I use the European pool (although I could use one even closer to home), "europe.pool.ntp.org". If all else fails, use "pool.ntp.org" but only whilst you debug. Find a local NTP server for the final code.

### Timezone (optional)
Before I get the time the first time in the sketch I set the timezone for the UK:
```
setenv("TZ", "GMT0BST,M3.5.0/01,M10.5.0/02", 1);
```
This step is optional; you will get GMT time (aka UTC) if you don't use it. 

Then I set some C-type variables to reflect the timezone:
```
 tzset();
```
### Getting the time
As you have doubtless already tried, I then just get the "local" time (it honours the timezone set above):
```
getLocalTime(&timeinfo)
```
The first time this is called the ESP32 will try and get the actual time from the NTP server pool you have specified. If this times out you will get January 1st, 1970 at midnight. Note that this should not "hang"; it will eventually time out.

### Repeated calls to local time
Every call to ```getLocalTime``` retrieves the locally synchronised time from the ESP32. Every hour (or thereabouts) it will resync the internal time with the NTP server. You don't have to do anything to make this happen. If the time resync fails, the ESP32 will attempt to resync on the next call.

Note that repeated calls to the actual NTP server (eg if you hack the ESP32 code or have a bug in your code) may result in your IP address being blacklisted for a while by the NTP server. Making repeated calls to ```getLocalTime()``` is the way to do it and let the ESP32 manage how often the time is retrieved and synchronised.

### Next steps
* You need to ensure you have a valid Wi-Fi and Internet connection.
* Use the steps I've outlined above
* If you repeatedly get 1st Jan 1970 00:00:00 try getting a page from the Internet to prove you have the necessary connectivity.

Let me know how this goes. If you just get 1st Jan 1970 post your minimum code that compiles here for inspection.

**Comment by usaotearoa** [comment]
Hi Ralph,
wow! Thank you for the detailed reply. Way beyond what I expected I'd get...
The ESP32 is connected to the internet and I can also ping the server from my PC, so my public IP shouldn't be blacklisted.

I found it the easiest to share the code, by just adding you to the repo as collaborator.
Hopefully that is ok.

But please don't spend too much of your time, I was just looking for a quick hint into the right direction, and I will try your suggestions on Monday morning, as it's Sunday 11pm here already :-(

If you decide to look, you'll find it's a heavily modified copy of your repository.

**Comment by RalphBacon** [comment]
### Summary
Loaded your code, compiled and after a few tweaks got this:
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[6][D][esp32-hal-cpu.c:214] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
In Setup
[    67][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   158][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 192.168.1.210, MASK: 255.255.255.0, GW: 192.168.1.254
[   157][V][WiFiGeneric.cpp:338] _arduino_event_cb(): STA Started
[   165][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 2 - STA_START
[   177][I][wifiHelper.h:56] begin(): WiFi begin success.
[   178][D][wifiHelper.h:63] connect(): Connecting to WiFi (60 second timeout)
[   436][V][WiFiGeneric.cpp:353] _arduino_event_cb(): STA Connected: SSID: Greypuss, BSSID: 08:86:3b:45:bc:42, Channel: 6, Auth: WPA_WPA2_PSK
[   438][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[   441][V][WiFiGeneric.cpp:367] _arduino_event_cb(): STA Got New IP:192.168.1.210
[   452][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[   460][D][WiFiGeneric.cpp:991] _eventCallback(): STA IP: 192.168.1.210, MASK: 255.255.255.0, GW: 192.168.1.254        
[   484][I][wifiHelper.h:79] connect(): Running on SSID Greypuss with IP 192.168.1.210, Channel 6, MAC address C4:4F:33:67:07:99F
After Wi-Fi
[   488][E][ntpHelper.h:52] setDaylightSavingOptions(): in setDaylightSavingOptions
[  1625][I][main.cpp:34] setup(): Current date/time is 18/12/2022 at 10:46:03
```
### The Fix (for me)
Whether the bit I "fixed" will work for you will depend on your computer network.

The **WfiFiHelper.h** file has this code in _your_ version:
```
// Try and get a static IP address
IPAddress local_IP(192, 168, 68, 210);
IPAddress gateway(192, 168, 68, 254);
IPAddress subnet(255, 255, 255, 0);
```

In my version, the local IP (and gateway) are on 192.168.1.x which is the most common local IP address (in case you don't know you can't make up any old address). Once I had done this it all sprang into life. Unless you have modified your local network try changing the 68 to 1 and see what happens.

### How to Check
Check your local IP of your computer. If on Windows you can fire up a CMD.exe window and type in:
```ipconfig```

![image](https://user-images.githubusercontent.com/20911308/208294263-5d2f486a-a30b-4dde-b25f-b66c866f09b9.png)
As you can see, my local IP addresses have 192.168.1.x at the start. What's yours?

**Comment by usaotearoa** [comment]
Thanks Ralph,
Truly appreciate the amount of work you put into this.
But unfortunately I'm renting, and do not control the network. I'll see if I can get access somehow to the router and modify the sub net

The hole day I've been poking in the code, looking for the problem, lol. And at the end it was just the ip, damn :-)

You're a Legend!
Thanks again
